export const helionHomeUrl:string = "https://helion.pl/"
export const helionSearchUrl:string = "https://helion.pl/search?szukaj=Testowanie%2520oprogramowania"
export const notFoundUrl:string = "https://helion.pl/search?qa=&serwisyall=0&szukaj=blablabla&wprzed=0&wprzyg=0&wsprzed=1&wyczerp=0"
export const searchProductrUrl:string = "https://helion.pl/search?qa=&serwisyall=&szukaj=Testowanie+oprogramowania&wprzed=&wprzyg=&wsprzed=&wyczerp="
export const cartUrl:string = "https://helion.pl/zakupy/"
